package com.greendaotest1204;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.greendaotest1204.bean.A;

import com.greendaotest1204.ADao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig aDaoConfig;

    private final ADao aDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        aDaoConfig = daoConfigMap.get(ADao.class).clone();
        aDaoConfig.initIdentityScope(type);

        aDao = new ADao(aDaoConfig, this);

        registerDao(A.class, aDao);
    }
    
    public void clear() {
        aDaoConfig.clearIdentityScope();
    }

    public ADao getADao() {
        return aDao;
    }

}
